apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Release.Name }}-nginx
 labels:
   app: hello-world
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
   matchLabels:
     app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: {{ .Values.image.repository }}
        ports:
         - name: http
           containerPort: 80
           protocol: TCP  

