apiVersion: v1
kind: Service
metadata:
 name: hello-world
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: hello-world
   
